config/routes.rb
Rails.application.routes.draw do
  get 'general/home'

  resources :congregations do
    get :speaker_list, on: :member
    resources :brothers, shallow: true do
      get :multiple, on: :collection
      post :add_multiple, on: :collection
    end

    get :multiple, on: :collection
    post :add_multiple, on: :collection
  end

  resources :outlines

  root 'general#home'

end

app/models/brother.rb
class Brother < ActiveRecord::Base
  include FriendlyId
  belongs_to :congregation
  has_and_belongs_to_many :outlines
  validates_presence_of :first_name, :last_name, :congregation_id

  friendly_id :full_name, use: :slugged

  def full_name(reverse: false)
    if reverse
      "#{last_name}, #{first_name}"
    else
      "#{first_name} #{last_name}"
    end
  end
end

app/models/congregation.rb
class Congregation < ActiveRecord::Base
  include FriendlyId
  has_many :brothers
  validates_presence_of :name, :meeting_day, :meeting_time

  friendly_id :name, use: :slugged

  scope :home_congregations, -> { where(my_congregation: true) }
  def self.my_home_congregation
    return home_congregations.first if home_congregations.any?
  end

  def self.my_congregation_selected?
    Congregation.where(my_congregation: true).any?
  end

  def time_and_day
    "#{meeting_day} #{meeting_time}"
  end

  def full_address
    result = [address || '']
    result.push city_state_zip unless city_state_zip.blank?
    result = result.join ', '
    result
  end

  def city_state_zip
    result = [city || '']
    result.push(state) unless state.blank?
    result = result.join ', '
    result += " #{zip}" unless zip.blank?
    result
  end
end

app/models/outline.rb
class Outline < ActiveRecord::Base
  has_and_belongs_to_many :brother
  validates_presence_of :title, :number
  validates_numericality_of :number

  def title_with_number
    "#{number} - #{title}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brothers_controller.rb
class BrothersController < ApplicationController
  before_action :set_congregation, only: [ :new, :create, :multiple, :add_multiple ]
  before_action :set_brother, only: [:show, :edit, :update, :destroy]

  def index
    @brothers = Brother.all
  end

  def show
  end

  def new
    @brother = Brother.new
  end

  def edit
  end

  def create
    @brother = @congregation.brothers.new(brother_params)

    respond_to do |format|
      if @brother.save
        format.html { redirect_to @brother.congregation, notice: 'Brother was successfully created.' }
        format.json { render :show, status: :created, location: @brother }
      else
        format.html { render :new }
        format.json { render json: @brother.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @brother.update(brother_params)
        format.html { redirect_to @brother, notice: 'Brother was successfully updated.' }
        format.json { render :show, status: :ok, location: @brother }
      else
        format.html { render :edit }
        format.json { render json: @brother.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @brother.destroy
    respond_to do |format|
      format.html { redirect_to brothers_url, notice: 'Brother was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def multiple

  end

  def add_multiple
    if params[:brothers].blank?
      redirect_to brothers_path
      return
    end

    brothers = params[:brothers].gsub! "\r", ''
    brothers = brothers.split "\n"
    brothers.each do |brother|
      @congregation.brothers.create(first_name: brother.split(' ').first,
                                    last_name: brother.split(' ').drop(1).join(' '))
    end

    redirect_to @congregation
  end

  private

  def set_brother
    @brother = Brother.friendly.find(params[:id])
  end

  def set_congregation
    @congregation = Congregation.friendly.find(params[:congregation_id])
  end

  def brother_params
    params.require(:brother).permit(:congregation_id, :first_name,
                                    :last_name, :phone, :email, :outline_ids => [])
  end
end

app/controllers/congregations_controller.rb
class CongregationsController < ApplicationController
  before_action :set_congregation, only: [:show, :edit, :update, :destroy,
                                          :speaker_list]

  def add_multiple
    if params[:congregations].blank?
      redirect_to congregations_path
      return
    end

    congregations = params[:congregations].delete("\r", '').split("\n")
    congregations.each do |cong|
      Congregation.create(name: cong,
                          meeting_time: '10:00 AM',
                          meeting_day: 'Sunday')
    end

    redirect_to congregations_path
  end

  def multiple
  end

  def index
    @congregations = Congregation.order(:name)
  end

  def show
  end

  def new
    @congregation = Congregation.new
  end

  def edit
  end

  def create
    @congregation = Congregation.new(congregation_params)
    if @congregation.save
      redirect_to congregations_url,
                  notice: 'Congregation was successfully created.'
    else
      render :new
    end
  end

  def update
    if @congregation.update(congregation_params)
      redirect_to congregations_url,
                  notice: 'Congregation was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @congregation.destroy
    respond_to do |format|
      format.html do
        redirect_to congregations_url, notice: 'Congregation was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def speaker_list
  end

  private

  def set_congregation
    @congregation = Congregation.friendly.find(params[:id])
  end

  def congregation_params
    params.require(:congregation).permit(:name, :number, :meeting_time, :address,
                                         :meeting_day, :kh_address, :kh_phone,
                                         :talk_coordinator_phone,
                                         :talk_coordinator,
                                         :city, :state, :zip, :my_congregation)
  end
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController
  def home
  end
end

app/controllers/outlines_controller.rb
class OutlinesController < ApplicationController
  before_action :set_outline, only: [:show, :edit, :update, :destroy]

  def index
    @outlines = Outline.order(:number)
  end

  def show
  end

  # GET /outlines/new
  def new
    @outline = Outline.new
  end

  # GET /outlines/1/edit
  def edit
  end

  def create
    @outline = Outline.new(outline_params)

    respond_to do |format|
      if @outline.save
        format.html { redirect_to outlines_url, notice: 'Outline was successfully created.' }
        format.json { render :show, status: :created, location: @outline }
      else
        format.html { render :new }
        format.json { render json: @outline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outlines/1
  # PATCH/PUT /outlines/1.json
  def update
    respond_to do |format|
      if @outline.update(outline_params)
        format.html { redirect_to outlines_url, notice: 'Outline was successfully updated.' }
        format.json { render :show, status: :ok, location: @outline }
      else
        format.html { render :edit }
        format.json { render json: @outline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outlines/1
  # DELETE /outlines/1.json
  def destroy
    @outline.destroy
    respond_to do |format|
      format.html { redirect_to outlines_url, notice: 'Outline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_outline
    @outline = Outline.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def outline_params
    params.require(:outline).permit(:title, :number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(text)
    content_for :title do
      text
    end
  end
end

app/helpers/brothers_helper.rb
module BrothersHelper
end

app/helpers/congregations_helper.rb
module CongregationsHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/outlines_helper.rb
module OutlinesHelper
end

app/views/brothers/_form.html.slim
= simple_form_for [@congregation, @brother] do |f|
  = f.error_notification

  /= hidden_field_tag :congregation_id, @congregation

  .form-inputs
    .row
      .col-xs-12.col-sm-6
        = f.input :first_name, input_html: { autofocus: true }
      .col-xs-12.col-sm-6
        = f.input :last_name
      .col-xs-12.col-sm-6
        = f.input :phone
      .col-xs-12.col-sm-6
        = f.input :email

  .form-actions
    = f.button :submit, 'Save', class: 'btn btn-primary'

app/views/brothers/edit.html.slim
- title "Edit #{@brother.full_name}"

.page-header
  h1
    => icon 'user'
    ' Edit #{@brother.full_name}
    small = @brother.congregation.name

ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Congregations', congregations_path
  li = link_to @brother.congregation.name, @brother.congregation
  li = link_to @brother.full_name, @brother
  li.active Edit


== render 'form'

app/views/brothers/index.html.slim
h1 Listing brothers

table
  thead
    tr
      th Congregation
      th First name
      th Last name
      th Phone
      th Email
      th
      th
      th

  tbody
    - @brothers.each do |brother|
      tr
        td = brother.congregation
        td = brother.first_name
        td = brother.last_name
        td = brother.phone
        td = brother.email
        td = link_to 'Show', brother
        td = link_to 'Edit', edit_brother_path(brother)
        td = link_to 'Destroy', brother, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Brother', new_brother_path

app/views/brothers/multiple.html.slim
- title 'Enter Multiple Brothers'
.page-header
  h1
    ' Add Multiple Brothers
    small Enter one name per line

ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Congregations', congregations_path
  li = link_to @congregation.name, @congregation
  li.active Add Multiple Brothers

= form_tag add_multiple_congregation_brothers_path do
  .row.bottom30
    .col-xs-12
      = label_tag :brothers, 'Brothers'

    .col-xs-12
      = text_area_tag :brothers, nil, class: 'form-control',
        required: true, rows: 10

  .row
    .col-xs-12
      = submit_tag 'Add Brothers', class: 'btn btn-primary'

app/views/brothers/new.html.slim
.page-header
  h1 New Brother in #{@congregation.name}

== render 'form'

app/views/brothers/show.html.slim
- title @brother.full_name

.page-header
  h1
    => @brother.full_name
    small = link_to 'Edit', edit_brother_path(@brother), class: 'btn-edit btn-link'

ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Congregations', congregations_path
  li = link_to @brother.congregation.name, @brother.congregation
  li.active = @brother.full_name

dl.dl-horizontal
  dt Congregation:
  dd = @brother.congregation.name

  dt First name:
  dd = @brother.first_name

  dt Last name:
  dd = @brother.last_name

  dt Phone:
  dd = @brother.phone

  dt Email:
  dd = @brother.email

.page-header
  h2
    ' Outlines Given by #{@brother.first_name}

p Check an outline number below to add it to the brothers list
= form_for [@congregation, @brother] do |f|
  = hidden_field_tag 'brother[outline_ids][]', nil

  ul.list-unstyled.list-inline.outlines-list
    - Outline.order(:number).each do |outline|
      li
        label
          => check_box_tag 'brother[outline_ids][]', outline.id, @brother.outlines.include?(outline),
            title: outline.title
          small = outline.number

  .row.top15
    .col-xs-12 = submit_tag 'Save', class: 'btn btn-primary'

app/views/congregations/_form.html.slim
= simple_form_for(@congregation) do |f|
  = f.error_notification

  .form-inputs

    .row
      .col-xs-12.col-sm-6
        = f.input :name, input_html: { autofocus: true }
      .col-xs-12.col-sm-6
        = f.input :meeting_time, label: 'Meeting Time'
      .col-xs-12.col-sm-6
        = f.input :meeting_day, label: 'Meeting Day'
      .col-xs-12.col-sm-6
        = f.input :address, label: 'Address'
      .col-xs-12.col-sm-6
        = f.input :city, label: 'City'
      .col-xs-12.col-sm-6
        = f.input :state, label: 'State'
      .col-xs-12.col-sm-6
        = f.input :zip, label: 'Zip'
      .col-xs-12.col-sm-6
        = f.input :kh_phone, label: 'Phone'
      .col-xs-12.col-sm-6
        = f.input :talk_coordinator
      .col-xs-12.col-sm-6
        = f.input :talk_coordinator_phone
      .col-xs-12.col-sm-6
        - if Congregation.my_home_congregation && Congregation.my_home_congregation.id != @congregation.id
          .alert.alert-info There is already a congregation selected as "My Congregation"
        - else
          = f.input :my_congregation, label: 'My Congregation'

  .form-actions
    = f.button :submit, 'Save', class: 'btn btn-primary'

app/views/congregations/edit.html.slim
- title "Edit #{@congregation.name}"

.page-header
  h1 Edit Congregation

ul.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Congregations', congregations_path
  li.active Edit

== render 'form'

app/views/congregations/index.html.slim
- title 'Congregations'

.page-header
  h1 Congregations

ul.breadcrumb
  li = link_to 'Home', root_path
  li.active Congregations

p
  => link_to 'New Congregation', new_congregation_path,
    class: 'btn-add'

  = link_to 'Add Multiple Congregations', multiple_congregations_path,
    class: 'btn btn-link'

table.table.top30.table-condensed
  thead
    tr
      th Name
      th Meeting Time
      th Address
      th Phone
      th

  tbody
    - @congregations.each do |congregation|
      tr
        td
          => link_to congregation.name, congregation
          = icon('star-o') if congregation.my_congregation?
        td = congregation.time_and_day
        td = congregation.address
        td = congregation.kh_phone
        td
          => link_to 'Edit', edit_congregation_path(congregation), class: 'btn-edit btn-xs'
          = link_to 'Destroy', congregation, data: {:confirm => 'Are you sure?'},
            method: :delete, class: 'btn-delete btn-xs'

app/views/congregations/multiple.html.slim
- title 'Enter Multiple Congregations'
.page-header
  h1
    ' Add Multiple Congregations
    small Enter one name per line

ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Congregations', congregations_path
  li.active Add Multiple

= form_tag add_multiple_congregations_path do
  .row.bottom30
    .col-xs-12
      = label_tag :congregations, 'Congregations'

    .col-xs-12
      = text_area_tag :congregations, nil, class: 'form-control',
        required: true, rows: 10

  .row
    .col-xs-12
      = submit_tag 'Add Congregations', class: 'btn btn-primary'

app/views/congregations/new.html.slim
- title 'New Congregation'

.page-header
  h1 New Congregation

ul.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Congregations', congregations_path
  li.active New

== render 'form'

app/views/congregations/show.html.slim
- title @congregation.name

.page-header
  h1
    => @congregation.name
    small = link_to 'Edit', edit_congregation_path(@congregation), class: 'btn-edit btn-link'

ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Congregations', congregations_path
  li.active = @congregation.name

dl.dl-horizontal
  dt Address:
  dd = @congregation.full_address

  dt Meeting time:
  dd = @congregation.time_and_day

  dt Phone:
  dd = @congregation.kh_phone

.row
 .col-xs-12.col-sm-6
  = link_to 'Speaker List', speaker_list_congregation_path(@congregation),
    class: 'btn btn-default'


h2 Brothers

p
  => link_to "Add Brother", new_congregation_brother_path(@congregation),
    class: 'btn-sm btn-add'

  = link_to icon('users') + 'Add Multiple Brothers', multiple_congregation_brothers_path(@congregation),
    class: 'btn-link btn-icon'

hr

- @congregation.brothers.order(:last_name, :first_name).each do |brother|
  = link_to brother.full_name, brother, class: 'btn-brother'

app/views/congregations/speaker_list.html.slim
- title("#{@congregation.name} Speaker List")

.page-header
  h1
    => @congregation.name
    small Outgoing Speakers

ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Congregations', congregations_path
  li = link_to @congregation.name, @congregation
  li.active 'Speaker List'

.row
  .col-xs-12
    dl
      dt Address
      dd
        = @congregation.address
        br
        = @congregation.city_state_zip
  .col-xs-12
    dl
      dt Meeting time:
      dd = @congregation.time_and_day

h2
  ' Outgoing Speakers
  small = link_to 'Prepare for copy', '', class: 'prepare-copy'

- @congregation.brothers.each do |brother|
  - if brother.outlines.any?
    .row.outgoing-speaker.bottom15
      .col-xs-12
        p
          strong> = brother.full_name
          = link_to 'Hide', '', class: 'hide-speaker'
      .col-xs-12
        p
          - brother.outlines.order(:number).each do |outline|
            span = outline.number

app/views/general/home.html.slim
.page-header
  h1 Talks

ul
  li = link_to 'Outlines', outlines_path
  li = link_to 'Congregations', congregations_path

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title = content_for?(:title) ? yield(:title) + ' - Talks' : "Talks"
    = stylesheet_link_tag    "application", media: "all"
    = csrf_meta_tags

    /! HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    /! WARNING: Respond.js doesn't work if you view the page via file:
    /! [if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    /![endif]

  body class="#{ controller.controller_name }"

    .container
      - flash.each do |name, msg|
        - unless controller.action_name == 'welcome'
          div class="alert alert-#{ name == :notice ? "success" : "error" }"
            a.close data-dismiss="alert" x
            = msg

      = yield

    = javascript_include_tag "application"

app/views/outlines/_form.html.slim
= simple_form_for @outline do |f|
  - if @outline.errors.any?
    #error_explanation
      h2 = "#{pluralize(@outline.errors.count, "error")} prohibited this outline from being saved:"
      ul
        - @outline.errors.full_messages.each do |message|
          li = message

  .field
    = f.input :number, input_html: { autofocus: true }

  .field
    = f.input :title

  .actions = f.submit 'Save', class: 'btn btn-primary'

app/views/outlines/edit.html.slim
.page-header
  h1 Edit Outline

ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Outlines', outlines_path
  li.active Edit


== render 'form'

app/views/outlines/index.html.slim
.page-header
  h1 Outlines

ol.breadcrumb
  li = link_to 'Home', root_path
  li.active = link_to 'Outlines', outlines_path

p = link_to 'New Outline', new_outline_path, class: 'btn-add'

table.table.table-condensed.table-striped.top30
  thead
    tr
      th Number
      th Title
      th

  tbody
    - @outlines.each do |outline|
      tr
        td.text-center = outline.number
        td = link_to outline.title, edit_outline_path(outline)
        td.text-center
          = link_to 'Destroy', outline, data: {:confirm => 'Are you sure?'},
            method: :delete, class: 'btn-delete btn-xs'

- if @outlines.count > 15
  p = link_to 'New Outline', new_outline_path, class: 'btn-add'

app/views/outlines/new.html.slim
h1 New Outline

ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Outlines', outlines_path
  li.active New

== render 'form'

app/views/outlines/show.html.slim
p#notice = notice

p
  strong Title:
  = @outline.title
p
  strong Number:
  = @outline.number

= link_to 'Edit', edit_outline_path(@outline)
'|
= link_to 'Back', outlines_path